[en]
  languageName = "English"
  languageCode = "en-US"
  weight = 10
  [en.params]
    languageISO = "EN"

[es]
  languageName = "Espa√±ol"
  languageCode = "es-ES"
  weight = 20
  [pt.params]
    languageISO = "ES"
